#!/bin/bash
# Phase Completion Hook for Dashboard Interface Project
# Triggers: memory save, git commit/push, summary document creation
#
# Usage: ./phase-completion.sh "Phase Name" "Summary Description"
#
# This hook is designed to be called at the end of each project phase
# to ensure proper documentation, version control, and context preservation.

set -e

PHASE_NAME="${1:-Unnamed Phase}"
SUMMARY_DESC="${2:-Phase completion}"
PROJECT_DIR="/home/mattb/projects/dashboard_interface_project"
DOCS_DIR="$PROJECT_DIR/docs/phase-summaries"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
DATE_READABLE=$(date +"%Y-%m-%d %H:%M:%S")
SAFE_PHASE_NAME=$(echo "$PHASE_NAME" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')

# Create docs directory if needed
mkdir -p "$DOCS_DIR"

# 1. Memory Operations via MCP
echo "=== Phase Completion: $PHASE_NAME ==="
echo "[1/4] Saving context to memory-keeper..."

# Create checkpoint
mcp-cli call memory-keeper/context_checkpoint "{
  \"name\": \"phase-$SAFE_PHASE_NAME-$TIMESTAMP\",
  \"description\": \"$SUMMARY_DESC\",
  \"includeFiles\": true,
  \"includeGitStatus\": true
}" 2>/dev/null || echo "Checkpoint creation skipped (MCP not available)"

# Save progress context
mcp-cli call memory-keeper/context_save "{
  \"key\": \"phase-complete-$SAFE_PHASE_NAME-$TIMESTAMP\",
  \"value\": \"$SUMMARY_DESC\",
  \"category\": \"progress\",
  \"priority\": \"high\",
  \"channel\": \"dashboard-project\"
}" 2>/dev/null || echo "Context save skipped (MCP not available)"

# 2. Git Operations
echo "[2/4] Committing and pushing changes..."
cd "$PROJECT_DIR"

# Stage all changes
git add -A

# Get list of changed files for the summary
CHANGED_FILES=$(git diff --cached --name-only 2>/dev/null || echo "No staged changes")

# Commit if there are changes
if [ -n "$(git diff --cached --name-only)" ]; then
    git commit -m "phase($SAFE_PHASE_NAME): $SUMMARY_DESC

Automated phase completion commit.
Timestamp: $DATE_READABLE

$(echo "$CHANGED_FILES" | head -20)
$([ $(echo "$CHANGED_FILES" | wc -l) -gt 20 ] && echo "... and more files")

Generated by phase-completion hook" || echo "Nothing to commit"

    # Push to remote
    git push origin main 2>/dev/null || echo "Push skipped (no remote or auth issue)"
fi

# Get recent commits for summary
RECENT_COMMITS=$(git log --oneline -10)
LATEST_COMMIT=$(git rev-parse --short HEAD)

# 3. Generate Summary Document
echo "[3/4] Generating phase summary document..."

SUMMARY_FILE="$DOCS_DIR/${TIMESTAMP}_${SAFE_PHASE_NAME}_summary.md"

cat > "$SUMMARY_FILE" << SUMMARY_EOF
# Phase Summary: $PHASE_NAME

**Date:** $DATE_READABLE
**Checkpoint ID:** phase-$SAFE_PHASE_NAME-$TIMESTAMP
**Latest Commit:** $LATEST_COMMIT

---

## Summary

$SUMMARY_DESC

---

## Git Commits (This Session)

\`\`\`
$RECENT_COMMITS
\`\`\`

---

## Files Changed

\`\`\`
$CHANGED_FILES
\`\`\`

---

## Next Steps

<!-- Add next steps here -->

---

## Restoration Instructions

To restore this checkpoint and continue work:

### 1. Memory Restoration
\`\`\`bash
# List available checkpoints
mcp-cli call memory-keeper/context_status '{}'

# Restore this specific checkpoint
mcp-cli call memory-keeper/context_restore_checkpoint '{
  "checkpointId": "phase-$SAFE_PHASE_NAME-$TIMESTAMP"
}'

# Get saved context
mcp-cli call memory-keeper/context_get '{
  "key": "phase-complete-$SAFE_PHASE_NAME-$TIMESTAMP"
}'
\`\`\`

### 2. Git Restoration
\`\`\`bash
cd $PROJECT_DIR
git checkout main
git pull origin main
git log --oneline -5  # Verify commits
\`\`\`

### 3. Environment Setup
\`\`\`bash
cd $PROJECT_DIR/backend
source venv/bin/activate
# Start server if needed
PYTHONPATH=. python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
\`\`\`

### 4. Verify State
\`\`\`bash
# Check extraction status
curl -s http://localhost:8000/api/v1/extraction/status | python3 -m json.tool

# Check database
source venv/bin/activate && python3 -c "
from sqlalchemy import create_engine, text
from app.core.config import settings
engine = create_engine(settings.DATABASE_URL)
with engine.connect() as conn:
    result = conn.execute(text('SELECT COUNT(*) FROM extracted_values'))
    print(f'Extracted values in DB: {result.scalar()}')
"
\`\`\`

---

## Context for Next Session

When resuming, tell Claude:

> "I'm continuing work on the Dashboard Interface Project. Last session completed the '$PHASE_NAME' phase. Please restore context from checkpoint 'phase-$SAFE_PHASE_NAME-$TIMESTAMP' and review the summary at $SUMMARY_FILE"

SUMMARY_EOF

echo "[4/4] Phase completion finished!"
echo ""
echo "Summary document: $SUMMARY_FILE"
echo "Checkpoint ID: phase-$SAFE_PHASE_NAME-$TIMESTAMP"
echo "Latest commit: $LATEST_COMMIT"
