"""Add extraction tables

Revision ID: 896670eb4597
Revises: 9fc6647c9407
Create Date: 2026-01-04 09:32:38.489224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896670eb4597'
down_revision: Union[str, None] = '9fc6647c9407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('files_discovered', sa.Integer(), nullable=False),
    sa.Column('files_processed', sa.Integer(), nullable=False),
    sa.Column('files_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_runs'))
    )
    op.create_index(op.f('ix_extraction_runs_id'), 'extraction_runs', ['id'], unique=False)
    op.create_index(op.f('ix_extraction_runs_status'), 'extraction_runs', ['status'], unique=False)
    op.create_table('extracted_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('field_category', sa.String(length=100), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('cell_address', sa.String(length=20), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], name=op.f('fk_extracted_values_extraction_run_id_extraction_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_extracted_values_property_id_properties'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_values')),
    sa.UniqueConstraint('extraction_run_id', 'property_name', 'field_name', name='uq_extracted_value')
    )
    op.create_index('idx_extracted_values_lookup', 'extracted_values', ['property_name', 'field_name'], unique=False)
    op.create_index(op.f('ix_extracted_values_extraction_run_id'), 'extracted_values', ['extraction_run_id'], unique=False)
    op.create_index(op.f('ix_extracted_values_field_name'), 'extracted_values', ['field_name'], unique=False)
    op.create_index(op.f('ix_extracted_values_id'), 'extracted_values', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_values_property_id'), 'extracted_values', ['property_id'], unique=False)
    op.create_index(op.f('ix_extracted_values_property_name'), 'extracted_values', ['property_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_values_property_name'), table_name='extracted_values')
    op.drop_index(op.f('ix_extracted_values_property_id'), table_name='extracted_values')
    op.drop_index(op.f('ix_extracted_values_id'), table_name='extracted_values')
    op.drop_index(op.f('ix_extracted_values_field_name'), table_name='extracted_values')
    op.drop_index(op.f('ix_extracted_values_extraction_run_id'), table_name='extracted_values')
    op.drop_index('idx_extracted_values_lookup', table_name='extracted_values')
    op.drop_table('extracted_values')
    op.drop_index(op.f('ix_extraction_runs_status'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    # ### end Alembic commands ###
